package com.sigpro.model;

public enum RolSistema {
	ADMINISTRADOR,
	PRODUCT_OWNER,
	PROJECT_MANAGER,
	ANALISTA_NEGOCIO,
	ARQUITECTO_SOFTWARE,
	DISENADOR_UI_UX,
	DESARROLLADOR_FRONTEND,
	DESARROLLADOR_BACKEND,
	QA_ENGINEER,
	DEVOPS_ENGINEER
}
